### ISSUE TITLE
Linux Mint 17 32bit compile error

### ISSUE THREAD

**Issue by bakoulis** [floooh/yakc#27]
First, `> ./fips gen` works well.
Then `> ./fips make yakcapp` give errors:
`> ./fips make yakcapp
=== dependency: 'oryol':
dir '/home/takis/tmp/oryol' exists
=== dependency: 'fips-unittestpp':
dir '/home/takis/tmp/fips-unittestpp' exists
=== dependency: 'fips-remotery':
dir '/home/takis/tmp/fips-remotery' exists
=== dependency: 'fips-glm':
dir '/home/takis/tmp/fips-glm' exists
=== dependency: 'fips-glfw':
dir '/home/takis/tmp/fips-glfw' exists
=== dependency: 'gliml':
dir '/home/takis/tmp/gliml' exists
=== dependency: 'fips-zlib':
dir '/home/takis/tmp/fips-zlib' exists
=== dependency: 'fips-vld':
dir '/home/takis/tmp/fips-vld' exists
=== dependency: 'fips-libcurl':
dir '/home/takis/tmp/fips-libcurl' exists
=== dependency: 'fips-soloud':
dir '/home/takis/tmp/fips-soloud' exists
=== dependency: 'oryol-imgui':
dir '/home/takis/tmp/oryol-imgui' exists
=== dependency: 'fips-imgui':
dir '/home/takis/tmp/fips-imgui' exists
=== building: linux-make-debug
make -j3 yakcapp
Scanning dependencies of target glfw3
Scanning dependencies of target Core
Scanning dependencies of target ALL_GENERATE
[  1%] Building CXX object oryol_Core/CMakeFiles/Core.dir/App.cc.o
[  1%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/context.c.o
Traceback (most recent call last):
  File "/home/takis/tmp/yakc-master/.fips-gen.py", line 56, in <module>
    processFile(attrs)
  File "/home/takis/tmp/yakc-master/.fips-gen.py", line 47, in processFile
    module.generate(input, out_src, out_hdr, args)
  File "/home/takis/tmp/oryol/fips-generators/Shader.py", line 1870, in generate
    shaderLibrary.validateShadersGLSL()
  File "/home/takis/tmp/oryol/fips-generators/Shader.py", line 1567, in validateShadersGLSL
    glslcompiler.validate(srcLines, 'vs', slVersion)
  File "/home/takis/tmp/oryol/fips-generators/util/glslcompiler.py", line 102, in validate
    output = callValidator(cmd)
  File "/home/takis/tmp/oryol/fips-generators/util/glslcompiler.py", line 38, in callValidator
    child = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
make[3]: *** [oryol-imgui_IMUI/CMakeFiles/ALL_GENERATE] Error 1
make[2]: *** [oryol-imgui_IMUI/CMakeFiles/ALL_GENERATE.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[  2%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/init.c.o
[  2%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/input.c.o
[  3%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/monitor.c.o
[  3%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/vulkan.c.o
[  3%] Building CXX object oryol_Core/CMakeFiles/Core.dir/Args.cc.o
[  4%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/window.c.o
[  4%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/x11_init.c.o
[  5%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/x11_monitor.c.o
[  6%] Building CXX object oryol_Core/CMakeFiles/Core.dir/Core.cc.o
[  6%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/x11_window.c.o
[  6%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/xkb_unicode.c.o
[  6%] Building CXX object oryol_Core/CMakeFiles/Core.dir/Log.cc.o
[  7%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/linux_joystick.c.o
[  7%] Building CXX object oryol_Core/CMakeFiles/Core.dir/Logger.cc.o
[  7%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/posix_time.c.o
[  8%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/posix_tls.c.o
[  9%] [  9%] Building CXX object oryol_Core/CMakeFiles/Core.dir/StackTrace.cc.o
Building CXX object oryol_Core/CMakeFiles/Core.dir/RunLoop.cc.o
[  9%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/glx_context.c.o
[ 10%] Building CXX object oryol_Core/CMakeFiles/Core.dir/Memory/Memory.cc.o
[ 11%] Building C object fips-glfw_glfw3/CMakeFiles/glfw3.dir/glfw/src/egl_context.c.o
[ 11%] Building CXX object oryol_Core/CMakeFiles/Core.dir/String/String.cc.o
Linking C static library libglfw3.a
[ 11%] Built target glfw3
[ 12%] Building CXX object oryol_Core/CMakeFiles/Core.dir/String/StringAtom.cc.o
[ 12%] Building CXX object oryol_Core/CMakeFiles/Core.dir/String/StringBuilder.cc.o
[ 13%] Building CXX object oryol_Core/CMakeFiles/Core.dir/String/StringConverter.cc.o
[ 13%] Building CXX object oryol_Core/CMakeFiles/Core.dir/String/WideString.cc.o
[ 13%] Building CXX object oryol_Core/CMakeFiles/Core.dir/String/stringAtomBuffer.cc.o
[ 14%] Building CXX object oryol_Core/CMakeFiles/Core.dir/String/stringAtomTable.cc.o
[ 14%] Building C object oryol_Core/CMakeFiles/Core.dir/String/ConvertUTF.c.o
[ 15%] Building CXX object oryol_Core/CMakeFiles/Core.dir/Threading/ThreadLocalData.cc.o
[ 15%] Building CXX object oryol_Core/CMakeFiles/Core.dir/Time/Clock.cc.o
[ 16%] Building CXX object oryol_Core/CMakeFiles/Core.dir/Trace.cc.o
Linking CXX static library libCore.a
[ 16%] Built target Core
make[1]: *** [src/yakcapp/CMakeFiles/yakcapp.dir/rule] Error 2
make: *** [yakcapp] Error 2
[ERROR] Failed to build config 'linux-make-debug' of project 'yakc-master'`

**Comment by floooh** [comment]
Yep, the problem is the 32-bit Linux. All the binary tools and libs (e.g. the glslangValidator shader compiler) have been compiled for 64-bit Linux only. It would be a whole lot of work supporting 32-bit Linux. Not something I'd like to do anytime soon (especially since the Android SDK also requires 64-bit Linux).
